// SPDX-FileCopyrightText: Kakao Corp. and SK telecom Co., Ltd.
// SPDX-License-Identifier: Apache-2.0

// Accessibility E2E in the real Electron window. The jsdom unit test has to disable
// color-contrast (no rendered colours there and no canvas), and it points here for that
// coverage, so this spec is the one that actually checks contrast, in both themes.
//
// axe-core is injected as source through evaluate() rather than addScriptTag: the app serves a
// "script-src 'self'" CSP that blocks injected tags, while evaluate() runs over the debugger
// protocol. The library is resolved from the frontend install that CI already sets up before
// this job, so the desktop package gains no dependency of its own.
import { expect, test } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";
import { launchApp, repoRoot, spdxFixture } from "./_helpers.mjs";

const AXE_SOURCE = fs.readFileSync(
  path.join(repoRoot, "frontend", "node_modules", "axe-core", "axe.min.js"),
  "utf8",
);

// Store the preference and reload rather than setting data-theme directly: this is the path a
// real user takes (the boot script in index.html resolves it before first paint), and a fresh
// document also guarantees a fresh axe, which matters because axe caches the colours it
// computed on a previous run and would otherwise grade the second theme with the first one's
// values.
async function loadInTheme(window, theme) {
  await window.evaluate((value) => localStorage.setItem("onot.theme", value), theme);
  await window.reload({ waitUntil: "load" });
  await expect(window.getByText("OSS Notice Generator")).toBeVisible({ timeout: 60000 });
  expect(await window.evaluate(() => document.documentElement.dataset.theme)).toBe(theme);
}

// Colours are read from computed style, so a control caught part-way through the fade back from
// its disabled state reports a blended colour and fails on timing rather than on design.
// toBeEnabled() is not enough: the disabled attribute clears at once while the opacity
// transition runs on after it. Waiting for every enabled control to be fully opaque is the
// condition axe actually depends on. (A disabled control keeps opacity 0.5 and axe skips it,
// which is correct: WCAG exempts inactive components.)
async function waitForOpaqueControls(window) {
  await window.waitForFunction(() =>
    [...document.querySelectorAll("button, input, label")].every(
      (el) => el.disabled || Number.parseFloat(getComputedStyle(el).opacity) === 1,
    ),
  );
}

async function runAxe(window) {
  await waitForOpaqueControls(window);
  await window.evaluate(AXE_SOURCE);
  // The preview iframe is sandboxed, so axe cannot reach into it; the notice document it holds
  // is generated by the renderer and checked on the Python side.
  return window.evaluate(() =>
    window.axe
      .run(
        { exclude: [["iframe"]] },
        { resultTypes: ["violations"], runOnly: ["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"] },
      )
      .then((results) =>
        results.violations.map((v) => ({
          id: v.id,
          impact: v.impact,
          // Carry each check's own data through: for color-contrast that is the measured ratio
          // and the two colours, which is what makes a failure fixable from the report alone.
          nodes: v.nodes.map((n) => ({
            target: n.target.join(" "),
            data: (n.any ?? []).map((check) => check.data),
          })),
        })),
      ),
  );
}

test("no axe violations in either theme, with a notice on screen", async () => {
  const { app, window } = await launchApp();
  try {
    // Audited in the default configuration, the one most people see. Settling is handled by
    // waitForOpaqueControls rather than by emulating reduced motion, which would audit a
    // configuration few users are in.
    for (const theme of ["light", "dark"]) {
      await loadInTheme(window, theme);

      // Exercise the populated state too: the parse card, the warning list and the preview frame
      // only exist once a file has gone through, and those carry the muted and warning tokens.
      await window.getByTestId("file-input").setInputFiles(spdxFixture);
      await expect(window.getByText("example-product")).toBeVisible({ timeout: 30000 });
      await window.getByTestId("generate-preview").click();
      await expect(window.locator("iframe")).toBeVisible({ timeout: 30000 });
      // Back to idle: while rendering, the primary button is disabled and exempt from contrast.
      await expect(window.getByTestId("generate-preview")).toBeEnabled({ timeout: 30000 });

      expect(await runAxe(window), `axe violations in the ${theme} theme`).toEqual([]);
    }
  } finally {
    await app.close();
  }
});

test("reduced motion collapses the transitions", async () => {
  const { app, window } = await launchApp();
  try {
    const duration = () =>
      window.evaluate(
        () => getComputedStyle(document.querySelector('[data-testid="dropzone"]')).transitionDuration,
      );
    // The default carries a real transition, and the preference has to remove it. Asserting both
    // halves is what makes this a test of the rule rather than of the default.
    await window.emulateMedia({ reducedMotion: "no-preference" });
    expect(Number.parseFloat(await duration())).toBeGreaterThan(0);

    await window.emulateMedia({ reducedMotion: "reduce" });
    expect(Number.parseFloat(await duration())).toBeLessThan(0.001);
  } finally {
    await app.close();
  }
});

test("the drop zone shows a focus indicator when reached by keyboard", async () => {
  const { app, window } = await launchApp();
  try {
    // Tab in from the top rather than calling focus(): :focus-visible is only guaranteed for
    // keyboard-driven focus, and a keyboard user is exactly who this indicator is for.
    let reached = false;
    for (let i = 0; i < 12 && !reached; i += 1) {
      await window.keyboard.press("Tab");
      reached = await window.evaluate(
        () => document.activeElement?.getAttribute("data-testid") === "file-input",
      );
    }
    expect(reached, "Tab never reached the file input").toBe(true);

    const outline = await window.evaluate(() => {
      const label = document.querySelector('[data-testid="dropzone"]');
      const style = getComputedStyle(label);
      return { style: style.outlineStyle, width: style.outlineWidth, color: style.outlineColor };
    });
    expect(outline.style).not.toBe("none");
    expect(Number.parseFloat(outline.width)).toBeGreaterThan(0);
  } finally {
    await app.close();
  }
});
